src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MaintenanceRequestHelper.cls
public class MaintenanceRequestHelper {
    
    public static void updateWorkOrders(List<Case> updatedCases){
        List<Case> futureMaintenenCases = new List<Case>();
        List<Case> closedCased = [Select Id,Type,Status,Equipment__r.Maintenance_Cycle__c,Vehicle__c,Equipment__c  from Case where status ='Closed' and Type in ('Routine Maintenance','Repair ') and Id in :updatedCases];
        for (Case closedCase : closedCased) {
            Date futureDate = date.today();
            Date today = date.today();
            Date partsExpirationDate = today.addDays((Integer)closedCase.Equipment__r.Maintenance_Cycle__c);
//            if(futureDate>partsExpirationDate){
                futureDate = partsExpirationDate;
//            }
            Case futureMCase = new Case(Vehicle__c=closedCase.Vehicle__c,Type='Routine Maintenance',Subject='Routine Maintenance',Date_Reported__c=today ,Equipment__c=closedCase.Equipment__c,Date_Due__c=futureDate);
            futureMaintenenCases.add(futureMCase);
        }

        insert futureMaintenenCases;

    }        
    
}