src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Inventory__c</fullName>
        <label>Current Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Replacement_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replacement Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MaintenanceRequestHelperTest.cls
/**
 * Created by syurks on 2/12/2018.
 */

@IsTest
private class MaintenanceRequestHelperTest {

    @TestSetup
    static void setup(){


    }

    static testMethod void testBehavior() { 
        Account account = new Account(Name='raja-NY',BillingState ='NY');
        insert account;
        Vehicle__c vehicle = new Vehicle__c(Air_Conditioner__c=true,Awning__c='Manual',Backup_Camera_Monitor__c=true,Bathroom_Hookup__c='Walk-In Shower',Bathrooms__c=2,Bedrooms__c=2);
        insert vehicle;

        Product2 product2 = new Product2(ProductCode='GC1040',Description='test data',Family='',Name='GenWatt Diesel 200kW',Cost__c=100,Current_Inventory__c=5,Lifespan_Months__c=2,Maintenance_Cycle__c=100,Replacement_Part__c=true,Warehouse_SKU__c='100099');

        insert product2;

        Case newCase = new Case(Type='Routine Maintenance',AccountId=account.Id,Vehicle__c = vehicle.Id,Equipment__c=product2.Id );

        insert newCase;

        newCase.status='Closed';

        update newCase;

        List<Case> futureCase = [Select Id,Status from Case where type=:newCase.Type and AccountId=:newCase.AccountId ];

        system.assert(futureCase.size()>0);
    }
}